name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kennyd3d/hello-world-app:latest

    #   - uses: clowdhaus/argo-cd-action/@main
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       command: version
    #       options: --client

    #   - name: Argo CD - Login
    #     uses: clowdhaus/argo-cd-action@main
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
    #       ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
    #       ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
    #     with:
    #       command: login
    #       options: ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }}

    #   - name: Argo CD - Sync Application
    #     uses: clowdhaus/argo-cd-action@main
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       command: app sync
    #       options: argo-demo --local ./deployment.yaml
