name: Build and Deploy 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Push 🛠️
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.prepare.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Preparing job
        id: prepare
        run: |
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          echo "SHA_SHORT=$SHA_SHORT"
          echo "::set-output name=sha_short::$SHA_SHORT"  # Set output for the job

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            kennyd3d/hello-world-app:${{ steps.prepare.outputs.sha_short }}
            kennyd3d/hello-world-app:dev

  argo-deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code from another repository
        uses: actions/checkout@v4
        with:
          repository: kennyd3d/argo-deployments
          path: ./argo-deployments
          token: ${{ secrets.GH_TOKEN }} # PAT for private repos

      - name: Force update local branch with remote
        working-directory: ./argo-deployments
        run: |
          git fetch origin main
          git reset --hard origin/main  # Resets to ensure you are in sync with the remote branch
          git clean -fd  # Removes any untracked files

      - name: Update image tag in values-dev.yaml
        working-directory: ./argo-deployments
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
          sudo chmod +x /usr/bin/yq
          yq e -i '.environments.dev.image = "kennyd3d/hello-world-app:${{ needs.build.outputs.sha_short }}"' ./argo-deployments/hello-world-app/values-dev.yaml

      - name: Commit files
        working-directory: ./argo-deployments
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[BOT] Update k8 deployment" || echo "No changes to commit"

      - name: Pull the latest changes from main
        working-directory: ./argo-deployments
        run: |
          git pull origin main --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GH_TOKEN }}
          directory: ./argo-deployments
          