name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.actor != 'github-actions[bot]' }} # Prevent bot-triggered commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Preparing job
        run: |
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV
          echo "Short SHA: $SHA_SHORT"

          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
          sudo chmod +x /usr/bin/yq

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update image tag in values.yaml
        env:
          IMAGE_TAG: ${{ env.SHA_SHORT }}
        run: |
          yq e -i '.environments.dev.image-tag = "${{ env.IMAGE_TAG }}"' ./CICD/hello-world-app/values.yaml

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kennyd3d/hello-world-app:${{ env.SHA_SHORT }}

      - name: Commit files
        run: |
          git add ./CICD/hello-world-app/values.yaml
          git commit -m "Update k8 deployment"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref_name }}
